### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by ru-sh** [nuxt-community/typescript-template#18]
I've just installed latest template by vue-cli and gotten the following error:

+-- UNMET PEER DEPENDENCY vue@^2.5.9
`-- UNMET PEER DEPENDENCY vuex@3.0.1

**Comment by PingZe1101** [comment]
I'va gotten same error, mark.

**Comment by qm3ster** [comment]
These are warnings, not errors.
Packages like `nuxt-class-component` expect these to be present. They are present, because `nuxt` depends on them. Feel free to also install them as your direct dependencies, but then you will be responsible for updating them, rather than just updating the `nuxt` package.
