### ISSUE TITLE
[generate error] Failed at nuxt generate script.

### ISSUE THREAD

**Issue by HeskeyBaozi** [nuxt-community/typescript-template#3]
Nice starter.

When I run the commands: `npm run dev`, `npm run build`, everything works well. But it reports an error when running the script `npm run generate`.

Here are logs:
![log1](http://wx1.sinaimg.cn/large/724c9a82gy1fforv2xfohj20r30smn0w.jpg)
![log2](http://wx1.sinaimg.cn/large/724c9a82gy1fforv400xdj20jg0smacv.jpg)

The project has been compiled because I can find the distribution folder. It failed at rendering url "/".

In the file `/store/index.js`:
```javascript
export const actions = {
  async nuxtServerInit({ commit }) { // <--
    const response = await axios.get("/random-data.json");
    const people = response.data.slice(0, 10);
    commit("setPeople", people);
  },
  select({ commit }, id) {
    commit("select", id);
  }
};
```
I edit it to that:
```javascript
export const actions = {
  async fetch({ commit }) { // <-- change nuxtServerInit() to fetch()
    const response = await axios.get("/random-data.json");
    const people = response.data.slice(0, 10);
    commit("setPeople", people);
  },
  select({ commit }, id) {
    commit("select", id);
  }
};
```
Then it works:
![log3](http://wx2.sinaimg.cn/large/724c9a82gy1ffos58cfr6j20mr0pztct.jpg)

I want to know the reasons why it crashes when there exists the function `nuxtServerInit()`..
Thank you.

**Comment by qm3ster** [comment]
This happens because `getPeople()` is trying to make a network request to an api (which is simulated by serving a static `static/random-data.json`) to populate the page data, but the "api" is not running.

When you are using a real api, this would not happen.

Solutions here include doing
Terminal 1: `npm run build && npm run start`
Terminal 2: `npm run generate`
this will work for any api, for example if you are using express

or in this case serving the static folder if you want to use that json.
Terminal 1: `npm install http-server` and `$(npm bin)/hs -p 3000 static/`
Terminal 2: `npm run generate`
