### ISSUE TITLE
Replace axios with @nuxtjs/axios

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/typescript-template#32]
Since we have a [@nuxtjs/axios](https://www.npmjs.com/package/@nuxtjs/axios) modification that is specifically crafted for use together with Nuxt it will be more logical to use it inside this template

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/typescript-template/issues/c26">#c26</a>)</em></sub></div>

**Comment by qm3ster** [comment]
Possible. But that's an extra dependency that might go unmaintained, and takes up space in the bundle.
Perhaps there should not be axios in this template at all, or it should at least be an option.
For instance, it causes #3
The template is called `typescript-template` not `axios-GSAP-tachyons-decorator-vuex_class-template`
At least the component classes make sense because they improve type information (directly related to this being typescript)

**Comment by AndrewBogdanovTSS** [comment]
Yeah, I agree. `tachyons` dependency bugs me the most, I'm not a fan of this lib and I don't see a huge benefit of its existing in the project. GSAP is also feeling unneeded here, it isn't even used anywhere in the code. Though I don't think `axios` should be removed since it showcases a workflow of requesting the data from the server which is quite common in any nuxt based app. We can make it optional via a question prompted during template initialization. What do you think?

**Comment by AndrewBogdanovTSS** [comment]
Created a seperate issue to address these dependencies update #34

**Comment by qm3ster** [comment]
What if you want to use isomorphic fetch or something instead of axios?
I agree to optional.

**Comment by hmsk** [comment]
Now it's running with `@nuxtjs/axios` since 22d0c56f20bfd588c264ba90b4a43e57f83fdb3f at all.
Open the issue if we intend to use axios directly 🤔
