### ISSUE TITLE
Nuxt Edge - Issue when running/building the project

### ISSUE THREAD

**Issue by naveensky** [nuxt-community/typescript-template#48]
### Version

[latest](https://github.com/nuxt-community/typescript-template/releases/tag/latest)

### Reproduction link

[not required](not required)

### Steps to reproduce

- Create a normal typescript project by `vue init nuxt-community/typescript-template my-project`
- Replace nuxt dependencies with nuxt-edge
- Replace ts-loader with latest version of ts-loader (compatible with webpack 4.x)
- Run command nuxt dev

### What is expected ?

The app to start normally as per this https://medium.com/nuxt/nuxt-2-is-coming-oh-yeah-212c1a9e1a67 which states no changes required for updating a nuxt 1.x project with nuxt 2.x project

### What is actually happening?

Receiving an error 

```
 INFO  Building project

✔ success Builder initialized
✔ success Nuxt files generated
✖ error TypeError: Cannot set property 'ts' of undefined
  at Builder.extendBuild.config (/Users/naveen/Downloads/nuxt/ts/modules/typescript.js:24:33)
  at Builder.<anonymous> (/usr/local/lib/node_modules/nuxt-edge/dist/nuxt.js:142:17)
  at WebpackClientConfig.config (/usr/local/lib/node_modules/nuxt-edge/dist/nuxt.js:11310:56)
  at Builder.webpackBuild (/usr/local/lib/node_modules/nuxt-edge/dist/nuxt.js:11881:56)
  at Builder.build (/usr/local/lib/node_modules/nuxt-edge/dist/nuxt.js:11592:16)
  at <anonymous>
```

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/typescript-template/issues/c38">#c38</a>)</em></sub></div>

**Comment by haleksandre** [comment]
The reason for this error is because Nuxt edge uses webpack 4 & the newer version of vue-loader. vue-loader changed how it handles components & Nuxt adjusted their webpack config accordingly. You see the webpack config changes [here](https://github.com/nuxt/nuxt.js/blob/ba5c9798e3800c0e6cab334039173672ffbddc25/lib/builder/webpack/base.js#L115-L126).

Because of this the object reference [here](https://github.com/nuxt-community/typescript-template/blob/6af12b03f798c7a0a50c209a98a833ac57753402/template/modules/typescript.js#L24) doesn't exist in Nuxt edge.

To fix it you must adjust the Typescript module `~/modules/typescript.js`. So it would look something like so:

```js
module.exports = function () {
  // Add .ts & .tsx extension to Nuxt
  this.nuxt.options.extensions.push('ts', 'tsx')

  // Extend webpack build
  this.extendBuild(config => {
    // Add TypeScript
    config.module.rules.push({
      test: /\.tsx?$/,
      loader: 'ts-loader',
      options: { appendTsSuffixTo: [/\.vue$/] }
    })

    // Add .ts extension in webpack resolve
    if (! config.resolve.extensions.includes('.ts')) {
      config.resolve.extensions.push('.ts')
    }

    // Add .tsx extension in webpack resolve
    if (! config.resolve.extensions.includes('.tsx')) {
      config.resolve.extensions.push('.tsx')
    }
  })
}
```

You'll also have to update ts-loader to version 4.x since version 3.x only support webpack 2 | 3.

After making those changes Nuxt edge should run without any issues.

**Comment by AndrewBogdanovTSS** [comment]
Just wanted to create same bug report! To make it work I just checked whether the object exists and if not - create a new one before pushing 'ts' extension into it. 
```
if (rule.loader === 'vue-loader') {
          if(!rule.options.loaders)rule.options.loaders = {}
        rule.options.loaders.ts = tsLoader
      }
```
but I guess @haleksandre provided a better solution

**Comment by haleksandre** [comment]
@AndrewBogdanovTSS It is testing for both. `?` means zero or one of whatever is before, in this case `x`. So the test will match `.ts` as well as `.tsx`.

If you don't plan on using `.tsx` you can remove `x?` from the test.

**Comment by naveensky** [comment]
I can confirm this works :). Great thanks @haleksandre.
